[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

 [functions]
node_bundler = "esbuild"
external_node_modules = ["mongoose", "express", "cors", "slugify", "serverless-http"]